name: Check Build

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Arduino Lint
        uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification
          library-manager: update
          project-type: library
